/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SucursalesImport } from './routes/sucursales'
import { Route as ConfiguracionImport } from './routes/configuracion'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SucursalesRoute = SucursalesImport.update({
  id: '/sucursales',
  path: '/sucursales',
  getParentRoute: () => rootRoute,
} as any)

const ConfiguracionRoute = ConfiguracionImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionImport
      parentRoute: typeof rootRoute
    }
    '/sucursales': {
      id: '/sucursales'
      path: '/sucursales'
      fullPath: '/sucursales'
      preLoaderRoute: typeof SucursalesImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracion': typeof ConfiguracionRoute
  '/sucursales': typeof SucursalesRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracion': typeof ConfiguracionRoute
  '/sucursales': typeof SucursalesRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/configuracion': typeof ConfiguracionRoute
  '/sucursales': typeof SucursalesRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/configuracion' | '/sucursales'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/configuracion' | '/sucursales'
  id: '__root__' | '/' | '/configuracion' | '/sucursales'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  SucursalesRoute: typeof SucursalesRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  SucursalesRoute: SucursalesRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/configuracion",
        "/sucursales"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/configuracion": {
      "filePath": "configuracion.tsx"
    },
    "/sucursales": {
      "filePath": "sucursales.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
